image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [317.57443,   0.     , 305.71729,
           0.     , 318.30077, 253.74026,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.031519, -0.045783, 0.006236, 0.003193, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [317.07825,   0.     , 305.23963,   0.     ,
           0.     , 317.63763, 253.21162,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
